# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

solve_QP <- function(Sigma, bound, maxiter, theta, linear_func, gradient, ever_active, nactive, kkt_tol, objective_tol) {
    .Call('_selectiveInference_solve_QP', PACKAGE = 'selectiveInference', Sigma, bound, maxiter, theta, linear_func, gradient, ever_active, nactive, kkt_tol, objective_tol)
}

find_one_row_debiasingM <- function(Sigma, row, bound, maxiter, theta, gradient, ever_active, nactive, kkt_tol, objective_tol) {
    .Call('_selectiveInference_find_one_row_debiasingM', PACKAGE = 'selectiveInference', Sigma, row, bound, maxiter, theta, gradient, ever_active, nactive, kkt_tol, objective_tol)
}

update1_ <- function(Q2, w, m, k) {
    .Call('_selectiveInference_update1_', PACKAGE = 'selectiveInference', Q2, w, m, k)
}

downdate1_ <- function(Q1, R, j0, m, n) {
    .Call('_selectiveInference_downdate1_', PACKAGE = 'selectiveInference', Q1, R, j0, m, n)
}

